<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <RootNamespace>NodeLib.Automation</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\XLib.Node\XLib.Node.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" Version="4.10.0" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.10.0" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.10.0" />
    <PackageReference Include="InputSimulator" Version="1.0.4" />
  </ItemGroup>

</Project>
